### ISSUE TITLE
Build a RESTful API (JSON)

### ISSUE THREAD

**Issue by siamkreative** [SiamKreative/STS#1]
Instead of waiting for the server-side response to render the page, render the page first and then AJAX to get the JSON data.

**Comment by SiamKreative** [comment]
https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4

**Comment by siamkreative** [comment]
Basically the question is: how to render the page asap (with loading spinner or skeleton screen) and then populate it asynchronously with data...?

**Comment by siamkreative** [comment]
### Ideal Setup?
- Backend: JSON REST API built with Express (see [routing](https://expressjs.com/en/guide/routing.html)) , hosted on Heroku.
- Frontend: HTML with vue.js, hosted on Netlify (Free for open source projects)

### Tutorials / Further reading
- https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4
- https://devcenter.heroku.com/articles/mean-apps-restful-api

**Comment by siamkreative** [comment]
![screenshot-www netlify com-2016-12-06-11-14-11](https://cloud.githubusercontent.com/assets/1778633/20912820/27e2dc7a-bba5-11e6-9244-cb04b23eb4df.png)
